### ISSUE TITLE
CI sometimes is broken

### ISSUE THREAD

**Issue by utam0k** [containers/youki#1121]

**Comment by utam0k** [comment]
@Furisto Can I ask you to write down what you know?

**Comment by YJDoc2** [comment]
Hey, which part is broken? I see that the run on master is working
Although there is an issue, where there is a daily run of podman_tests on my fork's master, and it constantly fails, even even though the commit that it is currently at passed it here

**Comment by utam0k** [comment]
@YJDoc2 cc; @adrianreber
I'm not sure but why rust-criu build failed 😭 
https://github.com/containers/youki/pull/1123

**Comment by YJDoc2** [comment]
In the CI logs, it is showing that rust-criu version 0.2.0 is used? even though all cargo.toml and lockfile has version 0.5.7 specfified in it?
```
   Compiling procfs v0.14.0
   Compiling rust-criu v0.2.0
error[E0583]: file not found for module `rpc`
 --> /home/runner/.cargo/registry/src/github.com-1ecc6299db9ec823/rust-criu-0.2.0/src/proto/mod.rs:1:1
```
The crates.io only has v 0.2 published : https://crates.io/crates/rust-criu , so there might be some mismatch somewhere, although I can't see why it is failing now, and didn't fail before

**Comment by stefins** [comment]
I think the CI was fixed with https://github.com/containers/youki/pull/1125

**Comment by utam0k** [comment]
@stefins Thanks for your effort! I tried to rebase #1123 , but still failed 😭

**Comment by YJDoc2** [comment]
> I think the CI was fixed with https://github.com/containers/youki/pull/1125

I believe this is regarding to one of my previous comments :
> Although there is an issue, where there is a daily run of podman_tests on my fork's master, and it constantly fails, even even though the commit that it is currently at passed it here

That is fixed by the PR they have mentioned. but as you have said, the PR CI is still broken for some reason. As I have mentioned, the CI is still using rust-criu v0.2.0 , even though the github has release v0.5.7, as crates io still only has release 0.2.0 , maybe that is causing the issue.

**Comment by utam0k** [comment]
Again :sob:

**Comment by YJDoc2** [comment]
Hey @utam0k , if you are talking about podman tests, it is due to the rust 1.64 changes, which should be fixed in #1211 . I tried to re run the workflow, but that still uses older commit, so is still failing at build stage, I think when it will run tomorrow,  it should work again.

**Comment by utam0k** [comment]
@YJDoc2 Thanks for your comment. I think we have trouble with the cache of ci.
https://github.com/containers/youki/pull/1206

**Comment by utam0k** [comment]
I cleared all caches.
